### ISSUE TITLE
Provide convenience method to mock multiple services in a single function call

### ISSUE THREAD

**Issue by c05mic** [maciej-gurban/angular-mockingbird#2]
Consider providing support for:

`am.mock(
    'Service1',
    'Service2',
    ...
);`

`am.inject()` supports this, so one'd expect the same convenience with `mock()`.

**Comment by maciej-gurban** [comment]
Not convinced this is a good idea. I have explicitly decided not to support this way of mocking to avoid having to figure out which of the passed services threw an error (since we don't have their names available). More verbose, but more sane to deal with, at least IMO.
